server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:29092
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/authentication_service
    username: postgres
    password: postgres
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

application:
  email-confirmation-token:
    expiration-minutes: 15
  kafka:
    topics:
      sendConfirmationEmail: sendConfirmationEmail
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    whitelist: /register,/login

