spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  kafka:
    bootstrap-servers: localhost:29092
    listener:
      ack-mode: record
    consumer:
      group-id: EmailConfirmation
      autoOffsetReset: earliest

kafka:
  topics:
    sendConfirmationEmail: sendConfirmationEmail
